### ISSUE TITLE
Unable to have two input nodes in current design. 

### ISSUE THREAD

**Issue by ryanwild7** [elphick/mass-composition#63]
from https://elphick.github.io/mass-composition/auto_examples/network_layouts.html

try this code:
mc_1, mc_2 = mc_feed.split(0.5, 'split 1', 'split 2')
mc_2.nodes[0] = 99 # random number that is a new node
mc_3, mc_4 = mc_1.split(0.5, 'split 3', 'split 4')
mc_5, mc_6 = mc_2.split(0.5, 'split 5', 'split 6')
mcn: MCNetwork = MCNetwork().from_streams([     mc_1, mc_2,
                                           mc_3, mc_4, mc_5, mc_6])

fig = mcn.plot_network(orientation='horizontal')
fig

**Comment by elphick** [comment]
Thanks for identifying this @ryanwild7.  It is true, presently the design requires a single feed edge/node.
Will consider how that constraint may be removed.  As a workaround, if the network being evaluated is simply for balance checking (per the example above), then consider redirecting the "flows" so that there is a single input node/edge.

**Comment by elphick** [comment]
When using a dag, two input nodes are possible.  Will create some examples before closing.
