### ISSUE TITLE
Test data has insufficient data

### ISSUE THREAD

**Issue by ryanwild7** [elphick/mass-composition#90]
df_data: pd.DataFrame = pd.read_csv(r'size_by_assay.csv')
    mc_size: MassComposition = MassComposition(df_data, name='Sample')
    print(mc_size)
Using version ^0.1.19 for mass-composition
KeyError: "Insufficient data supplied to solve mass-moisture: {'mass_wet': False, 'mass_dry': False, 'moisture': False}"

**Comment by ryanwild7** [comment]
mass_pct should be named mass_dry

**Comment by elphick** [comment]
Not so sure about that rename being the solution @ryanwild7.
The way the sample data was managed has recently changed, for the better I believe but documentation is lagging.

There are two places to grab data:
1) **elphick.mass_composition.datasets.datasets** where you will find methods like _demo_data_, and
2) **elphick.mass_composition.datasets.sample_data** where there are methods like _sample_data_.

Why?
Since I was trawling the public domain for good, real data, that needed to be appropriately referenced - that is 1) above, where I may invoke some light cleaning, but essentially those datasets will be largely structured as they are sourced.
The second location 2) is where the methods may load from 1) and apply transformations that prepare data ready for injection into the package.

Hopefully this helps.
I'll try and get some documentation added for this soon.  Will leave the issue open until then.

**Comment by elphick** [comment]
Added [documentation](https://elphick.github.io/mass-composition/datasets/datasets.html) and an [example](https://elphick.github.io/mass-composition/auto_examples/data_examples.html#sphx-glr-auto-examples-data-examples-py).
